- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Set default UFW policies to deny incoming and allow outgoing
  ufw:
    direction: incoming
    policy: deny

- name: Set default UFW policy to allow all outgoing traffic
  ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    name: 'OpenSSH'
    port: 22
    proto: tcp

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    name: 'HTTP'
    port: 80
    proto: tcp

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    name: 'HTTPS'
    port: 443
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
