App\Controller\Api\V1\Finance\XingGeneralDataLoadController:
    path: /api/v1/finance/xing
    controller: App\Controller\Api\V1\Finance\XingGeneralDataLoadController
    methods: GET

App\Controller\Api\V1\Gallery\GalleryImagesInfiniteScrollingLoadController:
    path: /api/v1/gallery/images
    controller: App\Controller\Api\V1\Gallery\GalleryImagesInfiniteScrollingLoadController
    methods: GET
App\Controller\Api\V1\Gallery\GalleryImagesFilterLoadController:
    path: /api/v1/gallery/images/filter
    controller: App\Controller\Api\V1\Gallery\GalleryImagesFilterLoadController
    methods: GET

App\Controller\Api\V1\Gallery\MemeGeneratorImagesInfiniteScrollingLoadController:
    path: /api/v1/meme-generator/images
    controller: App\Controller\Api\V1\Gallery\MemeGeneratorImagesInfiniteScrollingLoadController
    methods: GET
App\Controller\Api\V1\Gallery\MemeGeneratorImagesFilterLoadController:
    path: /api/v1/meme-generator/images/filter
    controller: App\Controller\Api\V1\Gallery\MemeGeneratorImagesFilterLoadController
    methods: GET

App\Controller\PrivacyPolicy\LoadController:
    path: /privacy-policy
    controller: App\Controller\PrivacyPolicy\LoadController
    methods: GET
App\Controller\Impressum\LoadController:
    path: /impressum
    controller: App\Controller\Impressum\LoadController
    methods: GET

#static:
#    path: /static-route
#    controller: App\Controller\DefaultController::index

# If you have a simple login on your website activate the following routes
# If you need registration or profile edit have a look at the:
# https://github.com/sulu/SuluCommunityBundle
#
#login:
#    path: /login
#    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#    defaults:
#        # the following template need to be created:
#        # see https://github.com/sulu/sulu/blob/2.x/templates/static/login.html.twig as example
#        template: static/login.html.twig
#
#logout:
#    path: /logout
