parameters:
    default_locale: en
    log_level: '%env(LOG_LEVEL)%'
    router.request_context.scheme: 'https'
    router.request_context.host: '%env(DEFAULT_URI)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    Sulu\Twig\Extensions\ImageExtension:
        arguments:
            $defaultAttributes:
                loading: 'lazy'
            $defaultAdditionalTypes:
                    webp: 'image/webp'
            $aspectRatio: true
            $imageFormatConfiguration: '%sulu_media.image.formats%'
        tags:
            - { name: 'twig.extension' }

    App\Controller\PrivacyPolicy\LoadController:
        arguments:
            - '@twig'
        tags:
            - { name: 'controller.service_arguments' }
    App\Controller\Impressum\LoadController:
        arguments:
            - '@twig'
        tags:
            - { name: 'controller.service_arguments' }
    App\Controller\Api\V1\Finance\XingFinanceDataLoadController:
        arguments:
            - '@App\Finance\XingFinanceDataByDexScreenerApiHandler'
            - '@api.v1.finance.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Finance\XingFinanceDataByDexScreenerApiHandler:
        arguments:
            - '@Xingxingcoin\ApiAdapter\Finance\XingFinanceDataByDexScreenerApiLoader'
            - '@App\Finance\Components\XingHappyModeGifUrlLoader'
            - '@App\Finance\Components\XingCalmModeGifUrlLoader'
            - '@App\Finance\Components\XingNeutralModeGifUrlLoader'
            - '@App\Finance\Components\XingUpsetModeGifUrlLoader'
            - '@App\Finance\Components\XingRageModeGifUrlLoader'
    Xingxingcoin\ApiAdapter\Finance\XingFinanceDataByDexScreenerApiLoader:
        arguments:
            - '@Xingxingcoin\ApiAdapter\Http\ApiHttpClient'
            - '@api.v1.finance.logger'
    App\Finance\Components\XingHappyModeGifUrlLoader:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@sulu_media.media_manager'
            - '@api.v1.finance.logger'
    App\Finance\Components\XingCalmModeGifUrlLoader:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@sulu_media.media_manager'
            - '@api.v1.finance.logger'
    App\Finance\Components\XingNeutralModeGifUrlLoader:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@sulu_media.media_manager'
            - '@api.v1.finance.logger'
    App\Finance\Components\XingUpsetModeGifUrlLoader:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@sulu_media.media_manager'
            - '@api.v1.finance.logger'
    App\Finance\Components\XingRageModeGifUrlLoader:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@sulu_media.media_manager'
            - '@api.v1.finance.logger'
    api.v1.finance.logging-handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%kernel.logs_dir%/finance_%kernel.environment%.log'
            - 14
            - '%log_level%'
            - true
            - 436
    api.v1.finance.logger:
        class: Monolog\Logger
        arguments:
            - 'finance'
        calls:
            - [ pushHandler, [ '@api.v1.finance.logging-handler' ] ]
    api.v1.gallery.logging-handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%kernel.logs_dir%/gallery_%kernel.environment%.log'
            - 14
            - '%log_level%'
            - true
            - 436
    api.v1.gallery.logger:
        class: Monolog\Logger
        arguments:
            - 'gallery'
        calls:
            - [ pushHandler, [ '@api.v1.gallery.logging-handler' ] ]
    http.logging-handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%kernel.logs_dir%/http_%kernel.environment%.log'
            - 14
            - '%log_level%'
            - true
            - 436
    http.logger:
        class: Monolog\Logger
        arguments:
            - 'http'
        calls:
            - [ pushHandler, [ '@http.logging-handler' ] ]

    App\Controller\Api\V1\Gallery\GalleryImagesInfiniteScrollingLoadController:
        arguments:
            - '@App\Gallery\GalleryImagesLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Controller\Api\V1\Gallery\MemeGeneratorImagesInfiniteScrollingLoadController:
        arguments:
            - '@App\Gallery\MemeGeneratorImagesLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Gallery\MemeGeneratorImagesLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@App\Gallery\Components\MediaUrlCollectionByDocumentLoader'
            - '@App\Gallery\Components\MediaUrlCollectionRandomizer'
    App\Gallery\GalleryImagesLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@App\Gallery\Components\MediaUrlCollectionByDocumentLoader'
            - '@App\Gallery\Components\MediaUrlCollectionRandomizer'
    App\Database\DocumentByPathLoader:
        arguments:
            - '@sulu_document_manager.document_manager'
            - '@api.v1.gallery.logger'

    App\Gallery\Components\MediaUrlCollectionByDocumentLoader:
        arguments:
            - '@sulu_media.media_manager'
            - '@App\Gallery\Components\DefaultNavigationMediaUrlLoader'
            - '@api.v1.gallery.logger'

    App\Gallery\Components\DefaultNavigationMediaUrlLoader:
        arguments:
            - '@sulu_website.navigation_mapper'

    Xingxingcoin\ApiAdapter\Http\ApiHttpClient:
        arguments:
            - '@Xingxingcoin\JsonValidator\Validation\OpisJsonValidator'
            - '@http_client'
            - '@http.logger'
    Xingxingcoin\JsonValidator\Validation\OpisJsonValidator: ~

    App\Controller\Api\V1\Gallery\GalleryImagesFilterLoadController:
        arguments:
            - '@App\Gallery\GalleryImagesFilterLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Gallery\GalleryImagesFilterLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@App\Gallery\Components\GalleryMediaCollectionByDocumentLoader'
            - '@App\Gallery\Components\GalleryMediaUrlCollectionByFilterGenerateHandler'
            - '@App\Gallery\Components\MediaUrlCollectionRandomizer'
    App\Gallery\Components\GalleryMediaCollectionByDocumentLoader:
        arguments:
            - '@sulu_media.media_manager'
            - '@App\Gallery\Components\DefaultNavigationMediaUrlLoader'
            - '@api.v1.gallery.logger'
    App\Gallery\Components\GalleryMediaUrlCollectionByFilterGenerateHandler:
        arguments:
            - '@App\Gallery\Components\MediaUrlCollectionByGifFilterGenerator'
            - '@App\Gallery\Components\MediaUrlCollectionByAllImagesFilterGenerator'
    App\Gallery\Components\MediaUrlCollectionByAllImagesFilterGenerator: ~
    App\Gallery\Components\MediaUrlCollectionByGifFilterGenerator: ~

    App\Controller\Api\V1\Gallery\MemeGeneratorImagesFilterLoadController:
        arguments:
            - '@App\Gallery\MemeGeneratorImagesFilterLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Gallery\MemeGeneratorImagesFilterLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Database\DocumentByPathLoader'
            - '@App\Gallery\Components\MemeGeneratorMediaCollectionByDocumentLoader'
            - '@App\Gallery\Components\MemeGeneratorMediaUrlCollectionByFilterGenerateHandler'
            - '@App\Gallery\Components\MediaUrlCollectionRandomizer'
    App\Gallery\Components\MemeGeneratorMediaCollectionByDocumentLoader:
        arguments:
            - '@sulu_media.media_manager'
            - '@App\Gallery\Components\DefaultNavigationMediaUrlLoader'
            - '@api.v1.gallery.logger'
    App\Gallery\Components\MemeGeneratorMediaUrlCollectionByFilterGenerateHandler:
        arguments:
            - '@App\Gallery\Components\MediaUrlCollectionByMemeTemplateFilterGenerator'
            - '@App\Gallery\Components\MediaUrlCollectionByMemeImageFilterGenerator'
    App\Gallery\Components\MediaUrlCollectionByMemeImageFilterGenerator: ~
    App\Gallery\Components\MediaUrlCollectionByMemeTemplateFilterGenerator: ~
    App\Gallery\Components\MediaUrlCollectionRandomizer: ~

