parameters:
    default_locale: en
    log_level: '%env(LOG_LEVEL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    Sulu\Twig\Extensions\ImageExtension:
        arguments:
            $defaultAttributes:
                loading: 'lazy'
            $defaultAdditionalTypes:
                    webp: 'image/webp'
            $aspectRatio: true
            $imageFormatConfiguration: '%sulu_media.image.formats%'
        tags:
            - { name: 'twig.extension' }

    App\Controller\Pages\WebsiteController:
        public: true
        arguments:
            - '@request_stack'
            - '@twig'
            - '@sulu_website.resolver.parameter'
            - '@sulu_core.webspace.request_analyzer'
            - '@sulu_http_cache.cache_lifetime.enhancer'
        tags:
            - { name: 'controller.service_arguments' }
            - { name: 'container.service_subscriber' }
            - { name: 'sulu.context', context: 'website' }

    App\Controller\Pages\HomeController:
        public: true
        arguments:
            - '@request_stack'
            - '@twig'
            - '@sulu_website.resolver.parameter'
            - '@sulu_core.webspace.request_analyzer'
            - '@sulu_http_cache.cache_lifetime.enhancer'
        tags:
            - { name: 'controller.service_arguments' }

    App\Controller\Pages\ExtendHomePageByXingDataController:
        public: true
        arguments:
            - '@request_stack'
            - '@twig'
            - '@sulu_website.resolver.parameter'
            - '@sulu_core.webspace.request_analyzer'
            - '@sulu_http_cache.cache_lifetime.enhancer'
            - '@App\Finance\DefaultXingFinanceDataByDexScreenerApiHandler'
        tags:
            - { name: 'controller.service_arguments' }
            - { name: 'container.service_subscriber' }
            - { name: 'sulu.context', context: 'website' }

    App\Finance\DefaultXingFinanceDataByDexScreenerApiHandler:
        arguments:
            - '@App\Finance\Components\XingFinanceDataByDexScreenerApiLoader'
            - '@pages.home.logger'
    App\Finance\Components\XingFinanceDataByDexScreenerApiLoader:
        arguments:
            - '@App\Http\ApiHttpClient'
            - '@pages.home.logger'

    pages.home.logging-handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%kernel.logs_dir%/home_%kernel.environment%.log'
            - 14
            - '%log_level%'
            - true
            - 436
    pages.home.logger:
        class: Monolog\Logger
        arguments:
            - 'home'
        calls:
            - [pushHandler, ['@pages.home.logging-handler']]
    api.v1.gallery.logging-handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%kernel.logs_dir%/gallery_%kernel.environment%.log'
            - 14
            - '%log_level%'
            - true
            - 436
    api.v1.gallery.logger:
        class: Monolog\Logger
        arguments:
            - 'gallery'
        calls:
            - [ pushHandler, [ '@api.v1.gallery.logging-handler' ] ]
    http.logging-handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%kernel.logs_dir%/http_%kernel.environment%.log'
            - 14
            - '%log_level%'
            - true
            - 436
    http.logger:
        class: Monolog\Logger
        arguments:
            - 'http'
        calls:
            - [ pushHandler, [ '@http.logging-handler' ] ]

    App\Controller\Api\V1\Gallery\GalleryImagesInfiniteScrollingLoadController:
        arguments:
            - '@App\Gallery\GalleryImagesLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Controller\Api\V1\Gallery\MemeGeneratorImagesInfiniteScrollingLoadController:
        arguments:
            - '@App\Gallery\MemeGeneratorImagesLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Gallery\MemeGeneratorImagesLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Gallery\Components\DocumentByPathLoader'
            - '@App\Gallery\Components\MediaUrlCollectionByDocumentLoader'
    App\Gallery\GalleryImagesLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Gallery\Components\DocumentByPathLoader'
            - '@App\Gallery\Components\MediaUrlCollectionByDocumentLoader'
    App\Gallery\Components\DocumentByPathLoader:
        arguments:
            - '@sulu_document_manager.document_manager'
            - '@api.v1.gallery.logger'

    App\Gallery\Components\MediaUrlCollectionByDocumentLoader:
        arguments:
            - '@sulu_media.media_manager'
            - '@App\Gallery\Components\DefaultNavigationMediaUrlLoader'
            - '@api.v1.gallery.logger'

    App\Gallery\Components\DefaultNavigationMediaUrlLoader:
        arguments:
            - '@sulu_website.navigation_mapper'

    App\Http\ApiHttpClient:
        arguments:
            - '@App\Json\OpisJsonValidator'
            - '@http_client'
            - '@http.logger'
    App\Json\OpisJsonValidator: ~

    App\Controller\Api\V1\Gallery\GalleryImagesFilterLoadController:
        arguments:
            - '@App\Gallery\GalleryImagesFilterLoadHandler'
            - '@api.v1.gallery.logger'
        tags:
            - { name: 'controller.service_arguments' }
    App\Gallery\GalleryImagesFilterLoadHandler:
        arguments:
            - '@sulu_document_manager.path_builder'
            - '@App\Gallery\Components\DocumentByPathLoader'
            - '@App\Gallery\Components\MediaCollectionByDocumentLoader'
            - '@App\Gallery\Components\MediaUrlCollectionByFilterGenerateHandler'
    App\Gallery\Components\MediaCollectionByDocumentLoader:
        arguments:
            - '@sulu_media.media_manager'
            - '@App\Gallery\Components\DefaultNavigationMediaUrlLoader'
            - '@api.v1.gallery.logger'
    App\Gallery\Components\MediaUrlCollectionByFilterGenerateHandler:
        arguments:
            - '@App\Gallery\Components\MediaUrlCollectionByGifFilterGenerator'
            - '@App\Gallery\Components\MediaUrlCollectionByAllImagesFilterGenerator'
    App\Gallery\Components\MediaUrlCollectionByAllImagesFilterGenerator: ~
    App\Gallery\Components\MediaUrlCollectionByGifFilterGenerator: ~
