- name: Download and install FrankenPHP
  ansible.builtin.shell: |
    curl -fsSL https://frankenphp.dev/install.sh | sh
  args:
    creates: frankenphp

- name: Move FrankenPHP binary to /usr/bin/
  command: mv frankenphp /usr/bin/frankenphp
  args:
    creates: /usr/bin/frankenphp

- name: Create Caddyfile for FrankenPHP
  copy:
    src: ./Caddyfile
    dest: /etc/caddy/Caddyfile

- name: Create systemd service file for FrankenPHP with Caddy
  copy:
    src: ./frankenphp-caddy.service
    dest: /etc/systemd/system/frankenphp-caddy.service
  notify:
    - Reload systemd

- name: Set cap_net_bind_service capability on frankenphp
  ansible.builtin.command:
    cmd: setcap cap_net_bind_service=+ep /usr/bin/frankenphp

- name: Reload systemd daemon to pick up new service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start FrankenPHP with Caddy service
  ansible.builtin.systemd:
    name: frankenphp-caddy.service
    enabled: yes
    state: started
