---
- name: Install necessary packages for deb.sury.org PHP repository
  ansible.builtin.apt:
    name:
      - lsb-release
      - ca-certificates
      - curl
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add the deb.sury.org PHP repository
  ansible.builtin.shell: |
    curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
    dpkg -i /tmp/debsuryorg-archive-keyring.deb
    echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
  args:
    creates: /etc/apt/sources.list.d/php.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PHP 8.4 packages
  ansible.builtin.apt:
    name:
      - php8.4-cli
      - php8.4-xml
    state: present
    update_cache: yes
