---
- name: Install necessary packages for ppa:ondrej/php repository
  ansible.builtin.apt:
    name:
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Ondrej PHP PPA
  ansible.builtin.shell: "LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php"
  args:
    creates: /etc/apt/sources.list.d/ondrej-php.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PHP 8.4 packages
  ansible.builtin.apt:
    name:
      - php8.4-cli
    state: present
    update_cache: yes
