---
- name: Install necessary packages for Ondrej PHP PPA
  ansible.builtin.apt:
    name:
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Ondrej PHP PPA
  ansible.builtin.shell: |
    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ondrej-php.list
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E5267A6C

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PHP 8.4 packages
  ansible.builtin.apt:
    name:
      - php8.4-cli
    state: present
    update_cache: yes
