- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Enable and start the fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Configure jail.local for SSH protection
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
