hosts:
  production:
    stage: production
    hostname: xingxing-memes.com
    remote_user: deploy
    deploy_path: /var/www/xing-meme-tool
    identity_file: /root/.ssh/id_rsa
    multiplexing: true
    sshOptions:
      UserKnownHostsFile: /dev/null
      StrictHostKeyChecking: no
    bin/php: php
    bin/local-php: php
    keep_releases: 5
    database: xing_meme_tool
    application: xing-meme-tool
    repository: git@github.com:xingxingcoin/website.git
    allow_anymous_stats: false
    default_timeout: 3600
    writable_mode: sticky
    http_user: caddy
    http_group: caddy
    cachetool_args: --web=SymfonyHttpClient --web-url=https://www.xingxing-memes.com/ --web-path=/var/www/xing-meme-tool/current/public --web-basic-auth="xing:W0oIlb4HzH"
