pipeline {
    agent any
    stages {
        stage('Install Volta') {
            steps {
                script {
                    sh 'curl https://get.volta.sh | bash'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
