pipeline {
    agent any
    stages {
        stage('Install Deployer') {
            steps {
                sh 'cd .deploy && composer install'
            }
        }
        stage('Deploy Prod') {
            steps {
                sh 'cd .deploy && php vendor/bon/dep -f deploy.php deploy:unlock production'
                sh 'cd .deploy && php vendor/bon/dep -f deploy.php deploy'
            }
        }
    }
}
