openapi: 3.0.3
info:
  title: Xing Xing Memetool Internal API
  contact:
    email: ariagholami@web.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://website.ddev.site/api/v1
tags:
  - name: finance
    description: Finance data
  - name: gallery
    description: Pictures of Xing Xing
paths:
  /api/v1/finance/xing:
    get:
      tags:
        - finance
      summary: Load basic xing finance data
      description: Load basic xing finance data by dexscreener
      operationId: loadXingFinanceData
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinanceData'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalServerError'
  /api/v1/gallery/images:
    get:
      tags:
        - gallery
      summary: Load up to 30 images for infinite scrolling
      description: Load up to 30 images for gallery by counter for infinite scrolling
      operationId: load30ImagesByCounterForInfiniteScrolling
      parameters:
        - name: counter
          in: query
          description: Counter that need to be considered for loading images
          required: false
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaUrls'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BadRequest'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalServerError'
  /api/v1/gallery/images/filter:
    get:
      tags:
        - gallery
      summary: Load up to 30 images for infinite scrolling
      description: Load up to 30 images for gallery by counter and filter for infinite scrolling
      operationId: load30ImagesByCounterAndFilterForInfiniteScrolling
      parameters:
        - name: counter
          in: query
          description: Counter that need to be considered for loading images
          required: false
          schema:
            type: number
        - name: filter
          in: query
          description: Filter that need to be considered for loading images
          required: true
          schema:
            type: string
            example:
              - 'gif'
              - 'image'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaUrls'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BadRequest'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalServerError'
  /api/v1/meme-generator/images:
    get:
      tags:
        - meme-generator
      summary: Load up to 30 images for infinite scrolling
      description: Load up to 30 images for meme-generator by counter for infinite scrolling
      operationId: load30ImagesByCounterForInfiniteScrolling
      parameters:
        - name: counter
          in: query
          description: Counter that need to be considered for loading images
          required: false
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaUrls'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BadRequest'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalServerError'
  /api/v1/meme-generator/images/filter:
    get:
      tags:
        - meme-generator
      summary: Load up to 30 images for infinite scrolling
      description: Load up to 30 images for meme-generator by counter and filter for infinite scrolling
      operationId: load30ImagesByCounterAndFilterForInfiniteScrolling
      parameters:
        - name: counter
          in: query
          description: Counter that need to be considered for loading images
          required: false
          schema:
            type: number
        - name: filter
          in: query
          description: Filter that need to be considered for loading images
          required: true
          schema:
            type: string
            example:
              - 'meme_template'
              - 'meme_image'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaUrls'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BadRequest'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    FinanceData:
      type: object
      required:
        - finance
        - url
      properties:
        finance:
          type: object
          required: [ marketCap, priceChange ]
          properties:
            marketCap:
              type: number
            priceChange:
              type: number
        url:
          type: string
    MediaUrls:
      type: object
      required:
        - urls
      properties:
        urls:
          type: array
          items:
            type: object
            required: [imageViewerUrl, mediaUrl]
            properties:
              imageViewerUrl:
                type: string
              mediaUrl:
                type: string
    BadRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Bad request.'
    InternalServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Internal server error.'
